### ISSUE TITLE
Sass::SyntaxError: Invalid CSS after "  }": expected selector or at-rule, was "}"

### ISSUE THREAD

**Issue by kntmrkm** [zweilove/css_splitter#53] opened 2015-06-22 14:22 UTC
I have other issue.
https://github.com/zweilove/css_splitter/issues/created_by/kntmrkm

but, I encounter another problem.

- Rails 4.2.2
- sass-3.4.14
- sprockets-3.2.0

Error message is 

`Sass::SyntaxError: Invalid CSS after "  }": expected selector or at-rule, was "}"`.

I'm cheking css compile by `rake assets:precompile`.

I know a file which cause the error.
I guess by delete part of the file.

I confirmed that Compile works without `config.assets.precompile += %w(application_split2.css)`.

This is code of the problem.

```
.datepicker.datepicker-inline {
  font-size: 16px;
  width: 100%;
  table {
    width: 100%;
  }
  table tr td, table tr th {
    padding: 1px 2px;
    height: 25px;
  }
}

// custom
/*
 * Datepicker for Bootstrap
 */
.datepicker {
  padding: 4px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  direction: ltr;
}
.datepicker-inline {
  width: 220px;
}
.datepicker.datepicker-rtl {
  direction: rtl;
}
.datepicker.datepicker-rtl table tr td span {
  float: right;
}
.datepicker-dropdown {
  top: 0;
  left: 0;
}
.datepicker-dropdown:before {
  content: '';
  display: inline-block;
  border-left: 7px solid transparent;
  border-right: 7px solid transparent;
  border-bottom: 7px solid #ccc;
  border-top: 0;
  border-bottom-color: rgba(0, 0, 0, 0.2);
  position: absolute;
}
.datepicker-dropdown:after {
  content: '';
  display: inline-block;
  border-left: 6px solid transparent;
  border-right: 6px solid transparent;
  border-bottom: 6px solid #ffffff;
  border-top: 0;
  position: absolute;
}
.datepicker-dropdown.datepicker-orient-left:before {
  left: 6px;
}
.datepicker-dropdown.datepicker-orient-left:after {
  left: 7px;
}
.datepicker-dropdown.datepicker-orient-right:before {
  right: 6px;
}
.datepicker-dropdown.datepicker-orient-right:after {
  right: 7px;
}
.datepicker-dropdown.datepicker-orient-top:before {
  top: -7px;
}
.datepicker-dropdown.datepicker-orient-top:after {
  top: -6px;
}
.datepicker-dropdown.datepicker-orient-bottom:before {
  bottom: -7px;
  border-bottom: 0;
  border-top: 7px solid #999;
}
.datepicker-dropdown.datepicker-orient-bottom:after {
  bottom: -6px;
  border-bottom: 0;
  border-top: 6px solid #ffffff;
}
.datepicker > div {
  display: none;
}
.datepicker.days div.datepicker-days {
  display: block;
}
.datepicker.months div.datepicker-months {
  display: block;
}
.datepicker.years div.datepicker-years {
  display: block;
}

//////////////////////////////////////////////////////////////
.datepicker table {
  margin: 0;
  user-select: none;
}
.datepicker td,
.datepicker th {
  text-align: center;
  width: 20px;
  height: 20px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  border: none;
}
.table-striped .datepicker table tr td,
.table-striped .datepicker table tr th {
  background-color: transparent;
}
.datepicker table tr td.day:hover,
.datepicker table tr td.day.focused {
  background: #eeeeee;
  cursor: pointer;
}
.datepicker table tr td.old,
.datepicker table tr td.new {
  color: #999999;
}
.datepicker table tr td.disabled,
.datepicker table tr td.disabled:hover {
  background: none;
  color: #999999;
  cursor: default;
}
.datepicker table tr td.selected,
.datepicker table tr td.selected:hover,
.datepicker table tr td.selected.disabled,
.datepicker table tr td.selected.disabled:hover {
  background-color: #9e9e9e;
  border-color: #808080;
  color: #fff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
}
.datepicker table tr td.selected:hover,
.datepicker table tr td.selected:hover:hover,
.datepicker table tr td.selected.disabled:hover,
.datepicker table tr td.selected.disabled:hover:hover,
.datepicker table tr td.selected:active,
.datepicker table tr td.selected:hover:active,
.datepicker table tr td.selected.disabled:active,
.datepicker table tr td.selected.disabled:hover:active,
.datepicker table tr td.selected.active,
.datepicker table tr td.selected:hover.active,
.datepicker table tr td.selected.disabled.active,
.datepicker table tr td.selected.disabled:hover.active,
.datepicker table tr td.selected.disabled,
.datepicker table tr td.selected:hover.disabled,
.datepicker table tr td.selected.disabled.disabled,
.datepicker table tr td.selected.disabled:hover.disabled,
.datepicker table tr td.selected[disabled],
.datepicker table tr td.selected:hover[disabled],
.datepicker table tr td.selected.disabled[disabled],
.datepicker table tr td.selected.disabled:hover[disabled] {
  background-color: #808080;
}
.datepicker table tr td.selected:active,
.datepicker table tr td.selected:hover:active,
.datepicker table tr td.selected.disabled:active,
.datepicker table tr td.selected.disabled:hover:active,
.datepicker table tr td.selected.active,
.datepicker table tr td.selected:hover.active,
.datepicker table tr td.selected.disabled.active,
.datepicker table tr td.selected.disabled:hover.active {
  background-color: #666666 \9;
}
.datepicker table tr td.active,
.datepicker table tr td.active:hover,
.datepicker table tr td.active.disabled,
.datepicker table tr td.active.disabled:hover {
  background-color: #428bca;
  border-color: #428bca;
  color: #fff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
}
.datepicker table tr td.active:hover,
.datepicker table tr td.active:hover:hover,
.datepicker table tr td.active.disabled:hover,
.datepicker table tr td.active.disabled:hover:hover,
.datepicker table tr td.active:active,
.datepicker table tr td.active:hover:active,
.datepicker table tr td.active.disabled:active,
.datepicker table tr td.active.disabled:hover:active,
.datepicker table tr td.active.active,
.datepicker table tr td.active:hover.active,
.datepicker table tr td.active.disabled.active,
.datepicker table tr td.active.disabled:hover.active,
.datepicker table tr td.active.disabled,
.datepicker table tr td.active:hover.disabled,
.datepicker table tr td.active.disabled.disabled,
.datepicker table tr td.active.disabled:hover.disabled,
.datepicker table tr td.active[disabled],
.datepicker table tr td.active:hover[disabled],
.datepicker table tr td.active.disabled[disabled],
.datepicker table tr td.active.disabled:hover[disabled] {
  background-color: #428bca;
}
.datepicker table tr td.active:active,
.datepicker table tr td.active:hover:active,
.datepicker table tr td.active.disabled:active,
.datepicker table tr td.active.disabled:hover:active,
.datepicker table tr td.active.active,
.datepicker table tr td.active:hover.active,
.datepicker table tr td.active.disabled.active,
.datepicker table tr td.active.disabled:hover.active {
  background-color: #428bca;
}
.datepicker table tr td span {
  display: block;
  width: 23%;
  height: 54px;
  line-height: 54px;
  float: left;
  margin: 1%;
  cursor: pointer;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
}
.datepicker table tr td span:hover {
  background: #eeeeee;
}
.datepicker table tr td span.disabled,
.datepicker table tr td span.disabled:hover {
  background: none;
  color: #999999;
  cursor: default;
}
.datepicker table tr td span.active,
.datepicker table tr td span.active:hover,
.datepicker table tr td span.active.disabled,
.datepicker table tr td span.active.disabled:hover {
  background-color: #428bca;
  border-color: #428bca;
  color: #fff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
}
.datepicker table tr td span.active:hover,
.datepicker table tr td span.active:hover:hover,
.datepicker table tr td span.active.disabled:hover,
.datepicker table tr td span.active.disabled:hover:hover,
.datepicker table tr td span.active:active,
.datepicker table tr td span.active:hover:active,
.datepicker table tr td span.active.disabled:active,
.datepicker table tr td span.active.disabled:hover:active,
.datepicker table tr td span.active.active,
.datepicker table tr td span.active:hover.active,
.datepicker table tr td span.active.disabled.active,
.datepicker table tr td span.active.disabled:hover.active,
.datepicker table tr td span.active.disabled,
.datepicker table tr td span.active:hover.disabled,
.datepicker table tr td span.active.disabled.disabled,
.datepicker table tr td span.active.disabled:hover.disabled,
.datepicker table tr td span.active[disabled],
.datepicker table tr td span.active:hover[disabled],
.datepicker table tr td span.active.disabled[disabled],
.datepicker table tr td span.active.disabled:hover[disabled] {
  background-color: #428bca;
}
.datepicker table tr td span.active:active,
.datepicker table tr td span.active:hover:active,
.datepicker table tr td span.active.disabled:active,
.datepicker table tr td span.active.disabled:hover:active,
.datepicker table tr td span.active.active,
.datepicker table tr td span.active:hover.active,
.datepicker table tr td span.active.disabled.active,
.datepicker table tr td span.active.disabled:hover.active {
  background-color: #428bca;
}
.datepicker table tr td span.old,
.datepicker table tr td span.new {
  color: #999999;
}
.datepicker th.datepicker-switch {
  width: 145px;
}
.datepicker thead tr:first-child th,
.datepicker tfoot tr th {
  cursor: pointer;
}
.datepicker thead tr:first-child th:hover,
.datepicker tfoot tr th:hover {
  background: #eeeeee;
}
.datepicker .cw {
  font-size: 10px;
  width: 12px;
  padding: 0 2px 0 5px;
  vertical-align: middle;
}
.datepicker thead tr:first-child th.cw {
  cursor: default;
  background-color: transparent;
}

//////////////////////////////////////////////////////////////
.input-append.date .add-on i,
.input-prepend.date .add-on i {
  cursor: pointer;
  width: 16px;
  height: 16px;
}
.input-daterange input {
  text-align: center;
}
.input-daterange input:first-child {
  border-radius: 3px 0 0 3px;
}
.input-daterange input:last-child {
  border-radius: 0 3px 3px 0;
}

//************************
.input-daterange .add-on {
  display: inline-block;
  width: auto;
  min-width: 16px;
  height: 20px;
  padding: 4px 5px;
  font-weight: normal;
  line-height: 20px;
  text-align: center;
  text-shadow: 0 1px 0 #ffffff;
  vertical-align: middle;
  background-color: #eeeeee;
  border: 1px solid #ccc;
  margin-left: -5px;
  margin-right: -5px;
}

//////////////////////////////////////////////////////////////
.datepicker.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  float: left;
  display: none;
  min-width: 160px;
  list-style: none;
  background-color: #ffffff;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 5px;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  background-clip: padding-box;
  color: #333333;
  font-size: 13px;
  line-height: 20px;
  padding: 5px;
}
.datepicker.dropdown-menu th,
.datepicker.datepicker-inline th,
.datepicker.dropdown-menu td,
.datepicker.datepicker-inline td {
  padding: 4px 5px;
}
```

and, Where the problem is 

```
.input-daterange .add-on {
  display: inline-block;
  width: auto;
  min-width: 16px;
  height: 20px;
  padding: 4px 5px;
  font-weight: normal;
  line-height: 20px;
  text-align: center;
  text-shadow: 0 1px 0 #ffffff;
  vertical-align: middle;
  background-color: #eeeeee;
  border: 1px solid #ccc;
  margin-left: -5px;
  margin-right: -5px;
}
```

If I delete part of the code like following. CSS compile works well.

```
.input-daterange .add-on {

}
```

**Comment by jhilden** [comment] 2015-06-23 08:24
In #26 the same error messages that you are reporting are also mentioned.  What version of `css_splitter` are you using?

**Comment by kntmrkm** [comment] 2015-06-23 08:45
Latest version 0.4.1.

**Comment by scriptfans** [comment] 2015-08-29 18:37
hi, I have the same problem, can you help me resolve it? thanks.

**Comment by rubenswieringa** [comment] 2015-08-31 10:44
In some cases the aforementioned error could be caused by a `@keyframes` block spanning from before to after the 4096 rule limit ([issue #38](https://github.com/zweilove/css_splitter/issues/38)). I made a pull-request for the [fix](https://github.com/nedap/css_splitter/tree/prevent-keyframes-split) here: **https://github.com/zweilove/css_splitter/pull/55**

**Comment by jhilden** [comment] 2015-08-31 16:50
@kntmrkm could you check if the fix by @rubenswieringa works for you?

**Comment by mityalebedev** [comment] 2015-10-21 14:54
Same problem with v0.4.2. Version 0.4.1 works well

**Comment by phallstrom** [comment] 2015-10-21 19:11
I too have the issue with 0.4.2. 0.4.1 no issue. Something in #55 is causing a problem.

**Comment by jhilden** [comment] 2015-10-21 22:09
could you provide some detailed information about the issue so it can be reproduced?  Ideally a reduced test case.

**Comment by phallstrom** [comment] 2015-10-21 22:11
@jhilden Might take me awhile, but I'll try.  We have a massive amount of CSS so not sure how to reproduce it in a way that makes it fail.

**Comment by cbeckr** [comment] 2015-11-15 17:18
Pull request #57 fixes this for us.

Here is a code snippet to reproduce - .no-media will become annotated with @media (min-width: 768px).
```
.nav-justified {
  width: 100%;

  > li {
    float: none;
    > a {
      text-align: center;
      margin-bottom: 5px;
    }
  }

  > .dropdown .dropdown-menu {
    top: auto;
    left: auto;
  }

  @media (min-width: 768px) {
    > li {
      display: table-cell;
      width: 1%;
      > a {
        margin-bottom: 0;
      }
    }
    > li {
      display: table-cell;
      width: 1%;
      > b {
        margin-bottom: 0;
      }
    }
    
  }
}

.no-media {
 display: none;
}
```

What happens is the following:
- In `split_string_into_rules`: The @media rule isn't detected by the regex since it contains leading spaces, so the closing tag won't be written into a separate rule
- In `extract_part`, `rule =~ /\A\s*}\z$/` will not detect the closing tag since it's not on a separate line. `current_media` will remain set for subsequent rules and will erroneously be repeated in the output. Subsequent media blocks will overwrite `current_media` but previous blocks are never closed - this leads to the syntax error reported by Sass.

**Comment by jhilden** [comment] 2015-11-15 17:36
Thanks a lot for the very detailed report @cbeckr   But I think it makes sense to open a new issue for that one, don't you agree?

Also, a failing test case or even a complete PR would be very welcome.  Since I'm not actively using this gem myself anymore, it's questionable if/when I will find time to work on a fix for this. Any help by anybody is appreciated.

**Comment by cbeckr** [comment] 2015-11-15 17:55
Thanks, to clarify - my sample yields the exact same error message. If @kntmrkm includes any @media blocks leading up to the sample snippet, this may very well be the same issue.

**Comment by jhilden** [comment] 2015-11-16 07:45
Fair enough.  Then we have to wait now until somebody adds some test coverage for the fix from #57 so this can be merged.

**Comment by scriptfans** [comment] 2015-11-25 07:09
+1

**Comment by jhilden** [comment] 2015-12-11 08:53
I'm closing this issue because #57 has been merged and version `0.4.3` released.  If the issue in this ticket should still be present, please reopen.

**Closed by jhilden** 2015-12-11 08:53 UTC
